plugins:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-rspec_rails
  - rubocop-capybara

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.x # match your Ruby version
  Exclude:
    - "db/schema.rb"
    - "db/migrate/**/*"
    - "bin/**/*"
    - "node_modules/**/*"
    - "vendor/**/*"

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"

Style/Documentation:
  Enabled: false
