development:
  adapter: redis
  url: redis://localhost:6379/1

test:
  adapter: test
  config: config/test_cable.yml

production:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  # url: <%= ENV['REDIS_URL'] %>
  channel_prefix: password_manager_production
